name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the website (Docker) 🔧
        run: |
          mkdir output.docker
          docker run \
            -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 \
            --tmpfs /tmp \
            -v $PWD:/data \
            sridca/emanote emanote -L "/data" gen /data/output.docker --allow-broken-links
          cp -r output.docker output
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
          # cname: yoursite.com
